### ISSUE TITLE
About Mask2Former

### ISSUE THREAD

**Issue by devinxzhang** [zkzhang98/MicroSeg#1]
Hi,

Thanks for your interesting work!

I would have one quick question. Since Mask2Former is adopted to generate proposals, why don't you directly use Mask2Former also for dense prediction, but use the deeplabv3 decoder? Thanks!

**Comment by zkzhang98** [comment]
Hi,
This is mainly because we consider pretrained Mask2Former as an _off-the-shelf_ proposal generator, insteading MicroSeg's main executing agency. We extract proposals only as an a prior knowledge.
Of course, directly dealing with CISS by Mask2Former is feasible, you can try it!
